platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest

inputs:
- name: source-code

outputs:
- name: target-restful

run:
  path: source-code/ci/tasks/package-restful.sh
