platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8

inputs:
- name: source-code

outputs:
- name: target-restful

run:
  path: source-code/ci/tasks/package-restful.sh
