platform: linux

image_resource:
  type: docker-image
  source:
    repository: springboot/ci-base-8-jdk

inputs:
- name: source-code

outputs:
- name: target-restful

run:
  path: source-code/ci/tasks/package-restful.sh
